blank_issues_enabled: false
contact_links:
- name: 🎓️  Learn More
  about: Not sure where to start? Read our contributing guide to learn more.
  url: https://github.com/QuanTizEd8/Test-Repo1000/blob/main/CONTRIBUTING.md
- name: 💬  Contact Us
  about: Have another inquiry or need help? Contact us directly!
  url: https://quantized8.github.io/Test-Repo1000/help/contact
